"""empty message

Revision ID: 1b5ba4c1b030
Revises: 35b6f043428d
Create Date: 2024-06-13 20:48:28.271944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b5ba4c1b030'
down_revision = '35b6f043428d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marca',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peca',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('etapa', sa.String(length=80), nullable=True),
    sa.Column('situacao', sa.Text(), nullable=False),
    sa.Column('codigo_rastreio', sa.String(length=30), nullable=True),
    sa.Column('data_entrega', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modelo', sa.String(length=80), nullable=True),
    sa.Column('acessorios', sa.String(length=200), nullable=True),
    sa.Column('fk_marca_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_marca_id'], ['marca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tecnico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('fk_nivel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_nivel_id'], ['nivel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orcamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantidade', sa.String(length=50), nullable=True),
    sa.Column('item', sa.String(length=50), nullable=True),
    sa.Column('valor_unit', sa.String(length=30), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=False),
    sa.Column('fk_tecnico_id', sa.Integer(), nullable=True),
    sa.Column('fk_cliente_id', sa.Integer(), nullable=True),
    sa.Column('fk_servico_id', sa.Integer(), nullable=True),
    sa.Column('fk_equipamento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['fk_equipamento_id'], ['equipamento.id'], ),
    sa.ForeignKeyConstraint(['fk_servico_id'], ['servico.id'], ),
    sa.ForeignKeyConstraint(['fk_tecnico_id'], ['tecnico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('usuario')
    with op.batch_alter_table('nivel', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nivel', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)

    op.create_table('usuario',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('fk_nivel_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_nivel_id'], ['nivel.id'], name='usuario_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('orcamento')
    op.drop_table('tecnico')
    op.drop_table('equipamento')
    op.drop_table('servico')
    op.drop_table('peca')
    op.drop_table('marca')
    op.drop_table('cliente')
    # ### end Alembic commands ###
